name: Build Check

# Sécurité : On limite les permissions au strict minimum (lecture du code uniquement)
permissions:
  contents: read

on:
  push:
    branches: [ "master", "main" ]
    tags:
    - 'v[0-9]*.[0-9]*.[0-9]*'      # Déclenche sur les tags de version (ex: v1.0.0)
  pull_request:
    branches: [ "master", "main" ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Restore dependencies
      run: dotnet restore SteganoApp.slnx

    - name: Build project
      run: dotnet build SteganoApp.slnx --configuration Release --no-restore

    - name: Release build (only on tags)
      if: startsWith(github.ref, 'refs/tags/')
      run: dotnet publish SteganoApp.slnx --configuration Release --no-restore -o ./publish

    - name: Upload build artifacts
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-artifact@v4
      with:
        name: stegano-release
        path: ./publish
